// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_base_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_base_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_base_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_base_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_base_2eproto;
namespace im {
namespace base {
class BaseRequest;
struct BaseRequestDefaultTypeInternal;
extern BaseRequestDefaultTypeInternal _BaseRequest_default_instance_;
class BaseResponse;
struct BaseResponseDefaultTypeInternal;
extern BaseResponseDefaultTypeInternal _BaseResponse_default_instance_;
class IMHeader;
struct IMHeaderDefaultTypeInternal;
extern IMHeaderDefaultTypeInternal _IMHeader_default_instance_;
}  // namespace base
}  // namespace im
PROTOBUF_NAMESPACE_OPEN
template<> ::im::base::BaseRequest* Arena::CreateMaybeMessage<::im::base::BaseRequest>(Arena*);
template<> ::im::base::BaseResponse* Arena::CreateMaybeMessage<::im::base::BaseResponse>(Arena*);
template<> ::im::base::IMHeader* Arena::CreateMaybeMessage<::im::base::IMHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace im {
namespace base {

enum ErrorCode : int {
  SUCCESS = 0,
  INVALID_REQUEST = 1,
  AUTH_FAILED = 2,
  NOT_FOUND = 3,
  PERMISSION_DENIED = 4,
  ALREADY_EXISTS = 5,
  PARAM_ERROR = 6,
  TIMEOUT = 7,
  SERVER_ERROR = 500,
  UNKNOWN_ERROR = 1000,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = SUCCESS;
constexpr ErrorCode ErrorCode_MAX = UNKNOWN_ERROR;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class IMHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.base.IMHeader) */ {
 public:
  inline IMHeader() : IMHeader(nullptr) {}
  ~IMHeader() override;
  explicit PROTOBUF_CONSTEXPR IMHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IMHeader(const IMHeader& from);
  IMHeader(IMHeader&& from) noexcept
    : IMHeader() {
    *this = ::std::move(from);
  }

  inline IMHeader& operator=(const IMHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMHeader& operator=(IMHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IMHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const IMHeader* internal_default_instance() {
    return reinterpret_cast<const IMHeader*>(
               &_IMHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IMHeader& a, IMHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(IMHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IMHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IMHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IMHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IMHeader& from) {
    IMHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IMHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.base.IMHeader";
  }
  protected:
  explicit IMHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kFromUidFieldNumber = 4,
    kToUidFieldNumber = 5,
    kTokenFieldNumber = 7,
    kDeviceIdFieldNumber = 8,
    kPlatformFieldNumber = 9,
    kSeqFieldNumber = 2,
    kCmdIdFieldNumber = 3,
    kTimestampFieldNumber = 6,
  };
  // string version = 1;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // string from_uid = 4;
  void clear_from_uid();
  const std::string& from_uid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_from_uid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_from_uid();
  PROTOBUF_NODISCARD std::string* release_from_uid();
  void set_allocated_from_uid(std::string* from_uid);
  private:
  const std::string& _internal_from_uid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_from_uid(const std::string& value);
  std::string* _internal_mutable_from_uid();
  public:

  // string to_uid = 5;
  void clear_to_uid();
  const std::string& to_uid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_to_uid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_to_uid();
  PROTOBUF_NODISCARD std::string* release_to_uid();
  void set_allocated_to_uid(std::string* to_uid);
  private:
  const std::string& _internal_to_uid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_to_uid(const std::string& value);
  std::string* _internal_mutable_to_uid();
  public:

  // string token = 7;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // string device_id = 8;
  void clear_device_id();
  const std::string& device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_id();
  PROTOBUF_NODISCARD std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // string platform = 9;
  void clear_platform();
  const std::string& platform() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_platform(ArgT0&& arg0, ArgT... args);
  std::string* mutable_platform();
  PROTOBUF_NODISCARD std::string* release_platform();
  void set_allocated_platform(std::string* platform);
  private:
  const std::string& _internal_platform() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_platform(const std::string& value);
  std::string* _internal_mutable_platform();
  public:

  // uint32 seq = 2;
  void clear_seq();
  uint32_t seq() const;
  void set_seq(uint32_t value);
  private:
  uint32_t _internal_seq() const;
  void _internal_set_seq(uint32_t value);
  public:

  // uint32 cmd_id = 3;
  void clear_cmd_id();
  uint32_t cmd_id() const;
  void set_cmd_id(uint32_t value);
  private:
  uint32_t _internal_cmd_id() const;
  void _internal_set_cmd_id(uint32_t value);
  public:

  // uint64 timestamp = 6;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:im.base.IMHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr from_uid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr to_uid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr platform_;
    uint32_t seq_;
    uint32_t cmd_id_;
    uint64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// -------------------------------------------------------------------

class BaseResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.base.BaseResponse) */ {
 public:
  inline BaseResponse() : BaseResponse(nullptr) {}
  ~BaseResponse() override;
  explicit PROTOBUF_CONSTEXPR BaseResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BaseResponse(const BaseResponse& from);
  BaseResponse(BaseResponse&& from) noexcept
    : BaseResponse() {
    *this = ::std::move(from);
  }

  inline BaseResponse& operator=(const BaseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseResponse& operator=(BaseResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BaseResponse* internal_default_instance() {
    return reinterpret_cast<const BaseResponse*>(
               &_BaseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BaseResponse& a, BaseResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BaseResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BaseResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BaseResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BaseResponse& from) {
    BaseResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BaseResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.base.BaseResponse";
  }
  protected:
  explicit BaseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kPayloadFieldNumber = 3,
    kErrorCodeFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // bytes payload = 3;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // .im.base.ErrorCode error_code = 1;
  void clear_error_code();
  ::im::base::ErrorCode error_code() const;
  void set_error_code(::im::base::ErrorCode value);
  private:
  ::im::base::ErrorCode _internal_error_code() const;
  void _internal_set_error_code(::im::base::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:im.base.BaseResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    int error_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// -------------------------------------------------------------------

class BaseRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.base.BaseRequest) */ {
 public:
  inline BaseRequest() : BaseRequest(nullptr) {}
  ~BaseRequest() override;
  explicit PROTOBUF_CONSTEXPR BaseRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BaseRequest(const BaseRequest& from);
  BaseRequest(BaseRequest&& from) noexcept
    : BaseRequest() {
    *this = ::std::move(from);
  }

  inline BaseRequest& operator=(const BaseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseRequest& operator=(BaseRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BaseRequest* internal_default_instance() {
    return reinterpret_cast<const BaseRequest*>(
               &_BaseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BaseRequest& a, BaseRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BaseRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BaseRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BaseRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BaseRequest& from) {
    BaseRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BaseRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.base.BaseRequest";
  }
  protected:
  explicit BaseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 1,
  };
  // bytes payload = 1;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // @@protoc_insertion_point(class_scope:im.base.BaseRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMHeader

// string version = 1;
inline void IMHeader::clear_version() {
  _impl_.version_.ClearToEmpty();
}
inline const std::string& IMHeader::version() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.version)
}
inline std::string* IMHeader::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.version)
  return _s;
}
inline const std::string& IMHeader::_internal_version() const {
  return _impl_.version_.Get();
}
inline void IMHeader::_internal_set_version(const std::string& value) {
  
  _impl_.version_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_version() {
  
  return _impl_.version_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_version() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.version)
  return _impl_.version_.Release();
}
inline void IMHeader::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  _impl_.version_.SetAllocated(version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.version)
}

// uint32 seq = 2;
inline void IMHeader::clear_seq() {
  _impl_.seq_ = 0u;
}
inline uint32_t IMHeader::_internal_seq() const {
  return _impl_.seq_;
}
inline uint32_t IMHeader::seq() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.seq)
  return _internal_seq();
}
inline void IMHeader::_internal_set_seq(uint32_t value) {
  
  _impl_.seq_ = value;
}
inline void IMHeader::set_seq(uint32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:im.base.IMHeader.seq)
}

// uint32 cmd_id = 3;
inline void IMHeader::clear_cmd_id() {
  _impl_.cmd_id_ = 0u;
}
inline uint32_t IMHeader::_internal_cmd_id() const {
  return _impl_.cmd_id_;
}
inline uint32_t IMHeader::cmd_id() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.cmd_id)
  return _internal_cmd_id();
}
inline void IMHeader::_internal_set_cmd_id(uint32_t value) {
  
  _impl_.cmd_id_ = value;
}
inline void IMHeader::set_cmd_id(uint32_t value) {
  _internal_set_cmd_id(value);
  // @@protoc_insertion_point(field_set:im.base.IMHeader.cmd_id)
}

// string from_uid = 4;
inline void IMHeader::clear_from_uid() {
  _impl_.from_uid_.ClearToEmpty();
}
inline const std::string& IMHeader::from_uid() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.from_uid)
  return _internal_from_uid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_from_uid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.from_uid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.from_uid)
}
inline std::string* IMHeader::mutable_from_uid() {
  std::string* _s = _internal_mutable_from_uid();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.from_uid)
  return _s;
}
inline const std::string& IMHeader::_internal_from_uid() const {
  return _impl_.from_uid_.Get();
}
inline void IMHeader::_internal_set_from_uid(const std::string& value) {
  
  _impl_.from_uid_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_from_uid() {
  
  return _impl_.from_uid_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_from_uid() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.from_uid)
  return _impl_.from_uid_.Release();
}
inline void IMHeader::set_allocated_from_uid(std::string* from_uid) {
  if (from_uid != nullptr) {
    
  } else {
    
  }
  _impl_.from_uid_.SetAllocated(from_uid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.from_uid_.IsDefault()) {
    _impl_.from_uid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.from_uid)
}

// string to_uid = 5;
inline void IMHeader::clear_to_uid() {
  _impl_.to_uid_.ClearToEmpty();
}
inline const std::string& IMHeader::to_uid() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.to_uid)
  return _internal_to_uid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_to_uid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.to_uid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.to_uid)
}
inline std::string* IMHeader::mutable_to_uid() {
  std::string* _s = _internal_mutable_to_uid();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.to_uid)
  return _s;
}
inline const std::string& IMHeader::_internal_to_uid() const {
  return _impl_.to_uid_.Get();
}
inline void IMHeader::_internal_set_to_uid(const std::string& value) {
  
  _impl_.to_uid_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_to_uid() {
  
  return _impl_.to_uid_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_to_uid() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.to_uid)
  return _impl_.to_uid_.Release();
}
inline void IMHeader::set_allocated_to_uid(std::string* to_uid) {
  if (to_uid != nullptr) {
    
  } else {
    
  }
  _impl_.to_uid_.SetAllocated(to_uid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.to_uid_.IsDefault()) {
    _impl_.to_uid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.to_uid)
}

// uint64 timestamp = 6;
inline void IMHeader::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t IMHeader::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t IMHeader::timestamp() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.timestamp)
  return _internal_timestamp();
}
inline void IMHeader::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void IMHeader::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:im.base.IMHeader.timestamp)
}

// string token = 7;
inline void IMHeader::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& IMHeader::token() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.token)
}
inline std::string* IMHeader::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.token)
  return _s;
}
inline const std::string& IMHeader::_internal_token() const {
  return _impl_.token_.Get();
}
inline void IMHeader::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_token() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.token)
  return _impl_.token_.Release();
}
inline void IMHeader::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.token)
}

// string device_id = 8;
inline void IMHeader::clear_device_id() {
  _impl_.device_id_.ClearToEmpty();
}
inline const std::string& IMHeader::device_id() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.device_id)
  return _internal_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_device_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.device_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.device_id)
}
inline std::string* IMHeader::mutable_device_id() {
  std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.device_id)
  return _s;
}
inline const std::string& IMHeader::_internal_device_id() const {
  return _impl_.device_id_.Get();
}
inline void IMHeader::_internal_set_device_id(const std::string& value) {
  
  _impl_.device_id_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_device_id() {
  
  return _impl_.device_id_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_device_id() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.device_id)
  return _impl_.device_id_.Release();
}
inline void IMHeader::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {
    
  } else {
    
  }
  _impl_.device_id_.SetAllocated(device_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.device_id_.IsDefault()) {
    _impl_.device_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.device_id)
}

// string platform = 9;
inline void IMHeader::clear_platform() {
  _impl_.platform_.ClearToEmpty();
}
inline const std::string& IMHeader::platform() const {
  // @@protoc_insertion_point(field_get:im.base.IMHeader.platform)
  return _internal_platform();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMHeader::set_platform(ArgT0&& arg0, ArgT... args) {
 
 _impl_.platform_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.IMHeader.platform)
}
inline std::string* IMHeader::mutable_platform() {
  std::string* _s = _internal_mutable_platform();
  // @@protoc_insertion_point(field_mutable:im.base.IMHeader.platform)
  return _s;
}
inline const std::string& IMHeader::_internal_platform() const {
  return _impl_.platform_.Get();
}
inline void IMHeader::_internal_set_platform(const std::string& value) {
  
  _impl_.platform_.Set(value, GetArenaForAllocation());
}
inline std::string* IMHeader::_internal_mutable_platform() {
  
  return _impl_.platform_.Mutable(GetArenaForAllocation());
}
inline std::string* IMHeader::release_platform() {
  // @@protoc_insertion_point(field_release:im.base.IMHeader.platform)
  return _impl_.platform_.Release();
}
inline void IMHeader::set_allocated_platform(std::string* platform) {
  if (platform != nullptr) {
    
  } else {
    
  }
  _impl_.platform_.SetAllocated(platform, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.platform_.IsDefault()) {
    _impl_.platform_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.IMHeader.platform)
}

// -------------------------------------------------------------------

// BaseResponse

// .im.base.ErrorCode error_code = 1;
inline void BaseResponse::clear_error_code() {
  _impl_.error_code_ = 0;
}
inline ::im::base::ErrorCode BaseResponse::_internal_error_code() const {
  return static_cast< ::im::base::ErrorCode >(_impl_.error_code_);
}
inline ::im::base::ErrorCode BaseResponse::error_code() const {
  // @@protoc_insertion_point(field_get:im.base.BaseResponse.error_code)
  return _internal_error_code();
}
inline void BaseResponse::_internal_set_error_code(::im::base::ErrorCode value) {
  
  _impl_.error_code_ = value;
}
inline void BaseResponse::set_error_code(::im::base::ErrorCode value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:im.base.BaseResponse.error_code)
}

// string error_message = 2;
inline void BaseResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& BaseResponse::error_message() const {
  // @@protoc_insertion_point(field_get:im.base.BaseResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BaseResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.BaseResponse.error_message)
}
inline std::string* BaseResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:im.base.BaseResponse.error_message)
  return _s;
}
inline const std::string& BaseResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void BaseResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* BaseResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* BaseResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:im.base.BaseResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void BaseResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.BaseResponse.error_message)
}

// bytes payload = 3;
inline void BaseResponse::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& BaseResponse::payload() const {
  // @@protoc_insertion_point(field_get:im.base.BaseResponse.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BaseResponse::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.BaseResponse.payload)
}
inline std::string* BaseResponse::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:im.base.BaseResponse.payload)
  return _s;
}
inline const std::string& BaseResponse::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void BaseResponse::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* BaseResponse::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* BaseResponse::release_payload() {
  // @@protoc_insertion_point(field_release:im.base.BaseResponse.payload)
  return _impl_.payload_.Release();
}
inline void BaseResponse::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.BaseResponse.payload)
}

// -------------------------------------------------------------------

// BaseRequest

// bytes payload = 1;
inline void BaseRequest::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& BaseRequest::payload() const {
  // @@protoc_insertion_point(field_get:im.base.BaseRequest.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BaseRequest::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:im.base.BaseRequest.payload)
}
inline std::string* BaseRequest::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:im.base.BaseRequest.payload)
  return _s;
}
inline const std::string& BaseRequest::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void BaseRequest::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* BaseRequest::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* BaseRequest::release_payload() {
  // @@protoc_insertion_point(field_release:im.base.BaseRequest.payload)
  return _impl_.payload_.Release();
}
inline void BaseRequest::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:im.base.BaseRequest.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace base
}  // namespace im

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::im::base::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::im::base::ErrorCode>() {
  return ::im::base::ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_base_2eproto
