// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: codec_service.proto

#include "codec_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace im {
namespace codec {
PROTOBUF_CONSTEXPR EncodeRequest::EncodeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_type_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EncodeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncodeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncodeRequestDefaultTypeInternal() {}
  union {
    EncodeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncodeRequestDefaultTypeInternal _EncodeRequest_default_instance_;
PROTOBUF_CONSTEXPR EncodeResponse::EncodeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.encoded_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EncodeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncodeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncodeResponseDefaultTypeInternal() {}
  union {
    EncodeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncodeResponseDefaultTypeInternal _EncodeResponse_default_instance_;
PROTOBUF_CONSTEXPR DecodeRequest::DecodeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.encoded_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DecodeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DecodeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DecodeRequestDefaultTypeInternal() {}
  union {
    DecodeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DecodeRequestDefaultTypeInternal _DecodeRequest_default_instance_;
PROTOBUF_CONSTEXPR DecodeResponse::DecodeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_type_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DecodeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DecodeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DecodeResponseDefaultTypeInternal() {}
  union {
    DecodeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DecodeResponseDefaultTypeInternal _DecodeResponse_default_instance_;
}  // namespace codec
}  // namespace im
static ::_pb::Metadata file_level_metadata_codec_5fservice_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_codec_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_codec_5fservice_2eproto = nullptr;

const uint32_t TableStruct_codec_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeRequest, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeRequest, _impl_.message_data_),
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeRequest, _impl_.message_type_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeResponse, _impl_.error_message_),
  PROTOBUF_FIELD_OFFSET(::im::codec::EncodeResponse, _impl_.encoded_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeRequest, _impl_.encoded_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _impl_.error_message_),
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _impl_.message_data_),
  PROTOBUF_FIELD_OFFSET(::im::codec::DecodeResponse, _impl_.message_type_name_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::im::codec::EncodeRequest)},
  { 9, -1, -1, sizeof(::im::codec::EncodeResponse)},
  { 18, -1, -1, sizeof(::im::codec::DecodeRequest)},
  { 25, -1, -1, sizeof(::im::codec::DecodeResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::im::codec::_EncodeRequest_default_instance_._instance,
  &::im::codec::_EncodeResponse_default_instance_._instance,
  &::im::codec::_DecodeRequest_default_instance_._instance,
  &::im::codec::_DecodeResponse_default_instance_._instance,
};

const char descriptor_table_protodef_codec_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023codec_service.proto\022\010im.codec\032\nbase.pr"
  "oto\"c\n\rEncodeRequest\022!\n\006header\030\001 \001(\0132\021.i"
  "m.base.IMHeader\022\024\n\014message_data\030\002 \001(\014\022\031\n"
  "\021message_type_name\030\003 \001(\t\"N\n\016EncodeRespon"
  "se\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message\030\002 \001"
  "(\t\022\024\n\014encoded_data\030\003 \001(\014\"%\n\rDecodeReques"
  "t\022\024\n\014encoded_data\030\001 \001(\014\"\214\001\n\016DecodeRespon"
  "se\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message\030\002 \001"
  "(\t\022!\n\006header\030\003 \001(\0132\021.im.base.IMHeader\022\024\n"
  "\014message_data\030\004 \001(\014\022\031\n\021message_type_name"
  "\030\005 \001(\t2\214\001\n\014CodecService\022=\n\006Encode\022\027.im.c"
  "odec.EncodeRequest\032\030.im.codec.EncodeResp"
  "onse\"\000\022=\n\006Decode\022\027.im.codec.DecodeReques"
  "t\032\030.im.codec.DecodeResponse\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_codec_5fservice_2eproto_deps[1] = {
  &::descriptor_table_base_2eproto,
};
static ::_pbi::once_flag descriptor_table_codec_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_codec_5fservice_2eproto = {
    false, false, 557, descriptor_table_protodef_codec_5fservice_2eproto,
    "codec_service.proto",
    &descriptor_table_codec_5fservice_2eproto_once, descriptor_table_codec_5fservice_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_codec_5fservice_2eproto::offsets,
    file_level_metadata_codec_5fservice_2eproto, file_level_enum_descriptors_codec_5fservice_2eproto,
    file_level_service_descriptors_codec_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_codec_5fservice_2eproto_getter() {
  return &descriptor_table_codec_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_codec_5fservice_2eproto(&descriptor_table_codec_5fservice_2eproto);
namespace im {
namespace codec {

// ===================================================================

class EncodeRequest::_Internal {
 public:
  static const ::im::base::IMHeader& header(const EncodeRequest* msg);
};

const ::im::base::IMHeader&
EncodeRequest::_Internal::header(const EncodeRequest* msg) {
  return *msg->_impl_.header_;
}
void EncodeRequest::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
EncodeRequest::EncodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:im.codec.EncodeRequest)
}
EncodeRequest::EncodeRequest(const EncodeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EncodeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_data_){}
    , decltype(_impl_.message_type_name_){}
    , decltype(_impl_.header_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_data().empty()) {
    _this->_impl_.message_data_.Set(from._internal_message_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_type_name().empty()) {
    _this->_impl_.message_type_name_.Set(from._internal_message_type_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::im::base::IMHeader(*from._impl_.header_);
  }
  // @@protoc_insertion_point(copy_constructor:im.codec.EncodeRequest)
}

inline void EncodeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_data_){}
    , decltype(_impl_.message_type_name_){}
    , decltype(_impl_.header_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EncodeRequest::~EncodeRequest() {
  // @@protoc_insertion_point(destructor:im.codec.EncodeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EncodeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_data_.Destroy();
  _impl_.message_type_name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.header_;
}

void EncodeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EncodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:im.codec.EncodeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_data_.ClearToEmpty();
  _impl_.message_type_name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EncodeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .im.base.IMHeader header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes message_data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message_type_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_message_type_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "im.codec.EncodeRequest.message_type_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EncodeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:im.codec.EncodeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .im.base.IMHeader header = 1;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // bytes message_data = 2;
  if (!this->_internal_message_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_message_data(), target);
  }

  // string message_type_name = 3;
  if (!this->_internal_message_type_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_type_name().data(), static_cast<int>(this->_internal_message_type_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "im.codec.EncodeRequest.message_type_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_message_type_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.codec.EncodeRequest)
  return target;
}

size_t EncodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:im.codec.EncodeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes message_data = 2;
  if (!this->_internal_message_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_message_data());
  }

  // string message_type_name = 3;
  if (!this->_internal_message_type_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_type_name());
  }

  // .im.base.IMHeader header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EncodeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EncodeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EncodeRequest::GetClassData() const { return &_class_data_; }


void EncodeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EncodeRequest*>(&to_msg);
  auto& from = static_cast<const EncodeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:im.codec.EncodeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_data().empty()) {
    _this->_internal_set_message_data(from._internal_message_data());
  }
  if (!from._internal_message_type_name().empty()) {
    _this->_internal_set_message_type_name(from._internal_message_type_name());
  }
  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::im::base::IMHeader::MergeFrom(
        from._internal_header());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EncodeRequest::CopyFrom(const EncodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:im.codec.EncodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncodeRequest::IsInitialized() const {
  return true;
}

void EncodeRequest::InternalSwap(EncodeRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_data_, lhs_arena,
      &other->_impl_.message_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_type_name_, lhs_arena,
      &other->_impl_.message_type_name_, rhs_arena
  );
  swap(_impl_.header_, other->_impl_.header_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EncodeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_codec_5fservice_2eproto_getter, &descriptor_table_codec_5fservice_2eproto_once,
      file_level_metadata_codec_5fservice_2eproto[0]);
}

// ===================================================================

class EncodeResponse::_Internal {
 public:
};

EncodeResponse::EncodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:im.codec.EncodeResponse)
}
EncodeResponse::EncodeResponse(const EncodeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EncodeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.encoded_data_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.encoded_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.encoded_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_encoded_data().empty()) {
    _this->_impl_.encoded_data_.Set(from._internal_encoded_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:im.codec.EncodeResponse)
}

inline void EncodeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.encoded_data_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.encoded_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.encoded_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EncodeResponse::~EncodeResponse() {
  // @@protoc_insertion_point(destructor:im.codec.EncodeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EncodeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
  _impl_.encoded_data_.Destroy();
}

void EncodeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EncodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:im.codec.EncodeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.encoded_data_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EncodeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "im.codec.EncodeResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      // bytes encoded_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_encoded_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EncodeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:im.codec.EncodeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "im.codec.EncodeResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  // bytes encoded_data = 3;
  if (!this->_internal_encoded_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_encoded_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.codec.EncodeResponse)
  return target;
}

size_t EncodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:im.codec.EncodeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // bytes encoded_data = 3;
  if (!this->_internal_encoded_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_encoded_data());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EncodeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EncodeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EncodeResponse::GetClassData() const { return &_class_data_; }


void EncodeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EncodeResponse*>(&to_msg);
  auto& from = static_cast<const EncodeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:im.codec.EncodeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (!from._internal_encoded_data().empty()) {
    _this->_internal_set_encoded_data(from._internal_encoded_data());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EncodeResponse::CopyFrom(const EncodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:im.codec.EncodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncodeResponse::IsInitialized() const {
  return true;
}

void EncodeResponse::InternalSwap(EncodeResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.encoded_data_, lhs_arena,
      &other->_impl_.encoded_data_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EncodeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_codec_5fservice_2eproto_getter, &descriptor_table_codec_5fservice_2eproto_once,
      file_level_metadata_codec_5fservice_2eproto[1]);
}

// ===================================================================

class DecodeRequest::_Internal {
 public:
};

DecodeRequest::DecodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:im.codec.DecodeRequest)
}
DecodeRequest::DecodeRequest(const DecodeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DecodeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.encoded_data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.encoded_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.encoded_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_encoded_data().empty()) {
    _this->_impl_.encoded_data_.Set(from._internal_encoded_data(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:im.codec.DecodeRequest)
}

inline void DecodeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.encoded_data_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.encoded_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.encoded_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DecodeRequest::~DecodeRequest() {
  // @@protoc_insertion_point(destructor:im.codec.DecodeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DecodeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.encoded_data_.Destroy();
}

void DecodeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DecodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:im.codec.DecodeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.encoded_data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DecodeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes encoded_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_encoded_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DecodeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:im.codec.DecodeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes encoded_data = 1;
  if (!this->_internal_encoded_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_encoded_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.codec.DecodeRequest)
  return target;
}

size_t DecodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:im.codec.DecodeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes encoded_data = 1;
  if (!this->_internal_encoded_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_encoded_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DecodeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DecodeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DecodeRequest::GetClassData() const { return &_class_data_; }


void DecodeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DecodeRequest*>(&to_msg);
  auto& from = static_cast<const DecodeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:im.codec.DecodeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_encoded_data().empty()) {
    _this->_internal_set_encoded_data(from._internal_encoded_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DecodeRequest::CopyFrom(const DecodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:im.codec.DecodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DecodeRequest::IsInitialized() const {
  return true;
}

void DecodeRequest::InternalSwap(DecodeRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.encoded_data_, lhs_arena,
      &other->_impl_.encoded_data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DecodeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_codec_5fservice_2eproto_getter, &descriptor_table_codec_5fservice_2eproto_once,
      file_level_metadata_codec_5fservice_2eproto[2]);
}

// ===================================================================

class DecodeResponse::_Internal {
 public:
  static const ::im::base::IMHeader& header(const DecodeResponse* msg);
};

const ::im::base::IMHeader&
DecodeResponse::_Internal::header(const DecodeResponse* msg) {
  return *msg->_impl_.header_;
}
void DecodeResponse::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
DecodeResponse::DecodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:im.codec.DecodeResponse)
}
DecodeResponse::DecodeResponse(const DecodeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DecodeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.message_type_name_){}
    , decltype(_impl_.header_){nullptr}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_data().empty()) {
    _this->_impl_.message_data_.Set(from._internal_message_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_type_name().empty()) {
    _this->_impl_.message_type_name_.Set(from._internal_message_type_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::im::base::IMHeader(*from._impl_.header_);
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:im.codec.DecodeResponse)
}

inline void DecodeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.message_type_name_){}
    , decltype(_impl_.header_){nullptr}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DecodeResponse::~DecodeResponse() {
  // @@protoc_insertion_point(destructor:im.codec.DecodeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DecodeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
  _impl_.message_data_.Destroy();
  _impl_.message_type_name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.header_;
}

void DecodeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DecodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:im.codec.DecodeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.message_data_.ClearToEmpty();
  _impl_.message_type_name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DecodeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "im.codec.DecodeResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      // .im.base.IMHeader header = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes message_data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_message_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message_type_name = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_message_type_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "im.codec.DecodeResponse.message_type_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DecodeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:im.codec.DecodeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "im.codec.DecodeResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  // .im.base.IMHeader header = 3;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // bytes message_data = 4;
  if (!this->_internal_message_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_message_data(), target);
  }

  // string message_type_name = 5;
  if (!this->_internal_message_type_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_type_name().data(), static_cast<int>(this->_internal_message_type_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "im.codec.DecodeResponse.message_type_name");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_message_type_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.codec.DecodeResponse)
  return target;
}

size_t DecodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:im.codec.DecodeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // bytes message_data = 4;
  if (!this->_internal_message_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_message_data());
  }

  // string message_type_name = 5;
  if (!this->_internal_message_type_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_type_name());
  }

  // .im.base.IMHeader header = 3;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DecodeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DecodeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DecodeResponse::GetClassData() const { return &_class_data_; }


void DecodeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DecodeResponse*>(&to_msg);
  auto& from = static_cast<const DecodeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:im.codec.DecodeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (!from._internal_message_data().empty()) {
    _this->_internal_set_message_data(from._internal_message_data());
  }
  if (!from._internal_message_type_name().empty()) {
    _this->_internal_set_message_type_name(from._internal_message_type_name());
  }
  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::im::base::IMHeader::MergeFrom(
        from._internal_header());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DecodeResponse::CopyFrom(const DecodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:im.codec.DecodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DecodeResponse::IsInitialized() const {
  return true;
}

void DecodeResponse::InternalSwap(DecodeResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_data_, lhs_arena,
      &other->_impl_.message_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_type_name_, lhs_arena,
      &other->_impl_.message_type_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DecodeResponse, _impl_.success_)
      + sizeof(DecodeResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(DecodeResponse, _impl_.header_)>(
          reinterpret_cast<char*>(&_impl_.header_),
          reinterpret_cast<char*>(&other->_impl_.header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DecodeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_codec_5fservice_2eproto_getter, &descriptor_table_codec_5fservice_2eproto_once,
      file_level_metadata_codec_5fservice_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace codec
}  // namespace im
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::im::codec::EncodeRequest*
Arena::CreateMaybeMessage< ::im::codec::EncodeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::im::codec::EncodeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::im::codec::EncodeResponse*
Arena::CreateMaybeMessage< ::im::codec::EncodeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::im::codec::EncodeResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::im::codec::DecodeRequest*
Arena::CreateMaybeMessage< ::im::codec::DecodeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::im::codec::DecodeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::im::codec::DecodeResponse*
Arena::CreateMaybeMessage< ::im::codec::DecodeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::im::codec::DecodeResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
