// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: command.proto
// Protobuf C++ Version: 5.29.3

#include "command.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace im {
namespace command {
}  // namespace command
}  // namespace im
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_command_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_command_2eproto = nullptr;
const ::uint32_t TableStruct_command_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_command_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rcommand.proto\022\nim.command*\354\007\n\tCommandI"
    "D\022\017\n\013CMD_UNKNOWN\020\000\022\016\n\tCMD_LOGIN\020\351\007\022\017\n\nCM"
    "D_LOGOUT\020\352\007\022\021\n\014CMD_REGISTER\020\353\007\022\026\n\021CMD_GE"
    "T_USER_INFO\020\354\007\022\031\n\024CMD_UPDATE_USER_INFO\020\355"
    "\007\022\024\n\017CMD_USER_ONLINE\020\356\007\022\025\n\020CMD_USER_OFFL"
    "INE\020\357\007\022\025\n\020CMD_SEND_MESSAGE\020\321\017\022\025\n\020CMD_PUL"
    "L_MESSAGE\020\322\017\022\027\n\022CMD_DELETE_MESSAGE\020\323\017\022\027\n"
    "\022CMD_RECALL_MESSAGE\020\324\017\022\024\n\017CMD_MESSAGE_AC"
    "K\020\325\017\022\032\n\025CMD_MESSAGE_DELIVERED\020\326\017\022\030\n\023CMD_"
    "MESSAGE_HISTORY\020\327\017\022\023\n\016CMD_ADD_FRIEND\020\271\027\022"
    "\026\n\021CMD_REMOVE_FRIEND\020\272\027\022\030\n\023CMD_GET_FRIEN"
    "D_LIST\020\273\027\022\034\n\027CMD_GET_FRIEND_REQUESTS\020\274\027\022"
    "\036\n\031CMD_HANDLE_FRIEND_REQUEST\020\275\027\022\024\n\017CMD_S"
    "EARCH_USER\020\276\027\022\025\n\020CMD_CREATE_GROUP\020\241\037\022\027\n\022"
    "CMD_GET_GROUP_INFO\020\242\037\022\027\n\022CMD_GET_GROUP_L"
    "IST\020\243\037\022\032\n\025CMD_MODIFY_GROUP_INFO\020\244\037\022\026\n\021CM"
    "D_INVITE_MEMBER\020\245\037\022\024\n\017CMD_KICK_MEMBER\020\246\037"
    "\022\031\n\024CMD_APPLY_JOIN_GROUP\020\247\037\022\023\n\016CMD_QUIT_"
    "GROUP\020\250\037\022\032\n\025CMD_GET_GROUP_MEMBERS\020\251\037\022\033\n\026"
    "CMD_GET_GROUP_MESSAGES\020\252\037\022\035\n\030CMD_TRANSFE"
    "R_GROUP_OWNER\020\253\037\022\030\n\023CMD_SET_GROUP_ADMIN\020"
    "\254\037\022\025\n\020CMD_PUSH_MESSAGE\020\211\'\022\033\n\026CMD_PUSH_BA"
    "TCH_MESSAGE\020\212\'\022\032\n\025CMD_PUSH_NOTIFICATION\020"
    "\213\'\022\024\n\017CMD_PUSH_SYSTEM\020\214\'\022\025\n\020CMD_PUSH_OFF"
    "LINE\020\215\'\022\022\n\rCMD_HEARTBEAT\020\251F\022\026\n\021CMD_SERVE"
    "R_NOTIFY\020\252F\022\025\n\020CMD_CLIENT_ERROR\020\253Fb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_command_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_command_2eproto = {
    false,
    false,
    1042,
    descriptor_table_protodef_command_2eproto,
    "command.proto",
    &descriptor_table_command_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_command_2eproto::offsets,
    file_level_enum_descriptors_command_2eproto,
    file_level_service_descriptors_command_2eproto,
};
namespace im {
namespace command {
const ::google::protobuf::EnumDescriptor* CommandID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_command_2eproto);
  return file_level_enum_descriptors_command_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommandID_internal_data_[] = {
    65536u, 2621440u, 4005u, 3002u, 5001u, 2001u, 4001u, 4009u, 5005u, 1004u, 2005u, 3005u, 4003u, 4007u, 4011u, 5003u, 9002u, 1002u, 1006u, 2003u, 2007u, 3004u, 3006u, 4002u, 4004u, 4006u, 4008u, 4010u, 4012u, 5002u, 5004u, 9001u, 9003u, 1001u, 1003u, 1005u, 1007u, 2002u, 2004u, 2006u, 3001u, 3003u, };
bool CommandID_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, CommandID_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace command
}  // namespace im
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_command_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
