// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

#include "command.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace im {
namespace command {
}  // namespace command
}  // namespace im
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_command_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_command_2eproto = nullptr;
const uint32_t TableStruct_command_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_command_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcommand.proto\022\nim.command*\200\010\n\tCommandI"
  "D\022\017\n\013CMD_UNKNOWN\020\000\022\021\n\rCMD_HEARTBEAT\020\001\022\025\n"
  "\021CMD_SERVER_NOTIFY\020\002\022\024\n\020CMD_CLIENT_ERROR"
  "\020\003\022\025\n\021CMD_REFRESH_TOKEN\020\004\022\016\n\tCMD_LOGIN\020\351"
  "\007\022\017\n\nCMD_LOGOUT\020\352\007\022\021\n\014CMD_REGISTER\020\353\007\022\026\n"
  "\021CMD_GET_USER_INFO\020\354\007\022\031\n\024CMD_UPDATE_USER"
  "_INFO\020\355\007\022\024\n\017CMD_USER_ONLINE\020\356\007\022\025\n\020CMD_US"
  "ER_OFFLINE\020\357\007\022\025\n\020CMD_SEND_MESSAGE\020\321\017\022\025\n\020"
  "CMD_PULL_MESSAGE\020\322\017\022\027\n\022CMD_DELETE_MESSAG"
  "E\020\323\017\022\027\n\022CMD_RECALL_MESSAGE\020\324\017\022\024\n\017CMD_MES"
  "SAGE_ACK\020\325\017\022\032\n\025CMD_MESSAGE_DELIVERED\020\326\017\022"
  "\030\n\023CMD_MESSAGE_HISTORY\020\327\017\022\023\n\016CMD_ADD_FRI"
  "END\020\271\027\022\026\n\021CMD_REMOVE_FRIEND\020\272\027\022\030\n\023CMD_GE"
  "T_FRIEND_LIST\020\273\027\022\034\n\027CMD_GET_FRIEND_REQUE"
  "STS\020\274\027\022\036\n\031CMD_HANDLE_FRIEND_REQUEST\020\275\027\022\024"
  "\n\017CMD_SEARCH_USER\020\276\027\022\025\n\020CMD_CREATE_GROUP"
  "\020\241\037\022\027\n\022CMD_GET_GROUP_INFO\020\242\037\022\027\n\022CMD_GET_"
  "GROUP_LIST\020\243\037\022\032\n\025CMD_MODIFY_GROUP_INFO\020\244"
  "\037\022\026\n\021CMD_INVITE_MEMBER\020\245\037\022\024\n\017CMD_KICK_ME"
  "MBER\020\246\037\022\031\n\024CMD_APPLY_JOIN_GROUP\020\247\037\022\023\n\016CM"
  "D_QUIT_GROUP\020\250\037\022\032\n\025CMD_GET_GROUP_MEMBERS"
  "\020\251\037\022\033\n\026CMD_GET_GROUP_MESSAGES\020\252\037\022\035\n\030CMD_"
  "TRANSFER_GROUP_OWNER\020\253\037\022\030\n\023CMD_SET_GROUP"
  "_ADMIN\020\254\037\022\025\n\020CMD_PUSH_MESSAGE\020\211\'\022\033\n\026CMD_"
  "PUSH_BATCH_MESSAGE\020\212\'\022\032\n\025CMD_PUSH_NOTIFI"
  "CATION\020\213\'\022\024\n\017CMD_PUSH_SYSTEM\020\214\'\022\025\n\020CMD_P"
  "USH_OFFLINE\020\215\'b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_command_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_command_2eproto = {
    false, false, 1062, descriptor_table_protodef_command_2eproto,
    "command.proto",
    &descriptor_table_command_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_command_2eproto::offsets,
    nullptr, file_level_enum_descriptors_command_2eproto,
    file_level_service_descriptors_command_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_command_2eproto_getter() {
  return &descriptor_table_command_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_command_2eproto(&descriptor_table_command_2eproto);
namespace im {
namespace command {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_command_2eproto);
  return file_level_enum_descriptors_command_2eproto[0];
}
bool CommandID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 3001:
    case 3002:
    case 3003:
    case 3004:
    case 3005:
    case 3006:
    case 4001:
    case 4002:
    case 4003:
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4008:
    case 4009:
    case 4010:
    case 4011:
    case 4012:
    case 5001:
    case 5002:
    case 5003:
    case 5004:
    case 5005:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace command
}  // namespace im
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
