// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: friend.proto

#include "friend.pb.h"
#include "friend.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace im {
namespace friend_ {

static const char* FriendService_method_names[] = {
  "/im.friend_.FriendService/ForwardPacket",
  "/im.friend_.FriendService/SendRequest",
  "/im.friend_.FriendService/RespondToRequest",
  "/im.friend_.FriendService/GetFriends",
  "/im.friend_.FriendService/GetPendingRequests",
};

std::unique_ptr< FriendService::Stub> FriendService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FriendService::Stub> stub(new FriendService::Stub(channel, options));
  return stub;
}

FriendService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ForwardPacket_(FriendService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendRequest_(FriendService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RespondToRequest_(FriendService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFriends_(FriendService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPendingRequests_(FriendService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FriendService::Stub::ForwardPacket(::grpc::ClientContext* context, const ::im::friend_::FriendPacketRequest& request, ::im::friend_::FriendPacketResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::friend_::FriendPacketRequest, ::im::friend_::FriendPacketResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ForwardPacket_, context, request, response);
}

void FriendService::Stub::async::ForwardPacket(::grpc::ClientContext* context, const ::im::friend_::FriendPacketRequest* request, ::im::friend_::FriendPacketResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::friend_::FriendPacketRequest, ::im::friend_::FriendPacketResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardPacket_, context, request, response, std::move(f));
}

void FriendService::Stub::async::ForwardPacket(::grpc::ClientContext* context, const ::im::friend_::FriendPacketRequest* request, ::im::friend_::FriendPacketResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardPacket_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::FriendPacketResponse>* FriendService::Stub::PrepareAsyncForwardPacketRaw(::grpc::ClientContext* context, const ::im::friend_::FriendPacketRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::friend_::FriendPacketResponse, ::im::friend_::FriendPacketRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ForwardPacket_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::FriendPacketResponse>* FriendService::Stub::AsyncForwardPacketRaw(::grpc::ClientContext* context, const ::im::friend_::FriendPacketRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncForwardPacketRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FriendService::Stub::SendRequest(::grpc::ClientContext* context, const ::im::friend_::AddFriendRequest& request, ::im::friend_::AddFriendResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::friend_::AddFriendRequest, ::im::friend_::AddFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendRequest_, context, request, response);
}

void FriendService::Stub::async::SendRequest(::grpc::ClientContext* context, const ::im::friend_::AddFriendRequest* request, ::im::friend_::AddFriendResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::friend_::AddFriendRequest, ::im::friend_::AddFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRequest_, context, request, response, std::move(f));
}

void FriendService::Stub::async::SendRequest(::grpc::ClientContext* context, const ::im::friend_::AddFriendRequest* request, ::im::friend_::AddFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::AddFriendResponse>* FriendService::Stub::PrepareAsyncSendRequestRaw(::grpc::ClientContext* context, const ::im::friend_::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::friend_::AddFriendResponse, ::im::friend_::AddFriendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::AddFriendResponse>* FriendService::Stub::AsyncSendRequestRaw(::grpc::ClientContext* context, const ::im::friend_::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FriendService::Stub::RespondToRequest(::grpc::ClientContext* context, const ::im::friend_::HandleFriendRequest& request, ::im::friend_::HandleFriendResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::friend_::HandleFriendRequest, ::im::friend_::HandleFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RespondToRequest_, context, request, response);
}

void FriendService::Stub::async::RespondToRequest(::grpc::ClientContext* context, const ::im::friend_::HandleFriendRequest* request, ::im::friend_::HandleFriendResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::friend_::HandleFriendRequest, ::im::friend_::HandleFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RespondToRequest_, context, request, response, std::move(f));
}

void FriendService::Stub::async::RespondToRequest(::grpc::ClientContext* context, const ::im::friend_::HandleFriendRequest* request, ::im::friend_::HandleFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RespondToRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::HandleFriendResponse>* FriendService::Stub::PrepareAsyncRespondToRequestRaw(::grpc::ClientContext* context, const ::im::friend_::HandleFriendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::friend_::HandleFriendResponse, ::im::friend_::HandleFriendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RespondToRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::HandleFriendResponse>* FriendService::Stub::AsyncRespondToRequestRaw(::grpc::ClientContext* context, const ::im::friend_::HandleFriendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRespondToRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FriendService::Stub::GetFriends(::grpc::ClientContext* context, const ::im::friend_::GetFriendListRequest& request, ::im::friend_::GetFriendListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::friend_::GetFriendListRequest, ::im::friend_::GetFriendListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFriends_, context, request, response);
}

void FriendService::Stub::async::GetFriends(::grpc::ClientContext* context, const ::im::friend_::GetFriendListRequest* request, ::im::friend_::GetFriendListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::friend_::GetFriendListRequest, ::im::friend_::GetFriendListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFriends_, context, request, response, std::move(f));
}

void FriendService::Stub::async::GetFriends(::grpc::ClientContext* context, const ::im::friend_::GetFriendListRequest* request, ::im::friend_::GetFriendListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFriends_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::GetFriendListResponse>* FriendService::Stub::PrepareAsyncGetFriendsRaw(::grpc::ClientContext* context, const ::im::friend_::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::friend_::GetFriendListResponse, ::im::friend_::GetFriendListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFriends_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::GetFriendListResponse>* FriendService::Stub::AsyncGetFriendsRaw(::grpc::ClientContext* context, const ::im::friend_::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFriendsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FriendService::Stub::GetPendingRequests(::grpc::ClientContext* context, const ::im::friend_::GetFriendRequestsRequest& request, ::im::friend_::GetFriendRequestsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::friend_::GetFriendRequestsRequest, ::im::friend_::GetFriendRequestsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPendingRequests_, context, request, response);
}

void FriendService::Stub::async::GetPendingRequests(::grpc::ClientContext* context, const ::im::friend_::GetFriendRequestsRequest* request, ::im::friend_::GetFriendRequestsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::friend_::GetFriendRequestsRequest, ::im::friend_::GetFriendRequestsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPendingRequests_, context, request, response, std::move(f));
}

void FriendService::Stub::async::GetPendingRequests(::grpc::ClientContext* context, const ::im::friend_::GetFriendRequestsRequest* request, ::im::friend_::GetFriendRequestsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPendingRequests_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::GetFriendRequestsResponse>* FriendService::Stub::PrepareAsyncGetPendingRequestsRaw(::grpc::ClientContext* context, const ::im::friend_::GetFriendRequestsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::friend_::GetFriendRequestsResponse, ::im::friend_::GetFriendRequestsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPendingRequests_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::friend_::GetFriendRequestsResponse>* FriendService::Stub::AsyncGetPendingRequestsRaw(::grpc::ClientContext* context, const ::im::friend_::GetFriendRequestsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPendingRequestsRaw(context, request, cq);
  result->StartCall();
  return result;
}

FriendService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FriendService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FriendService::Service, ::im::friend_::FriendPacketRequest, ::im::friend_::FriendPacketResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FriendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::friend_::FriendPacketRequest* req,
             ::im::friend_::FriendPacketResponse* resp) {
               return service->ForwardPacket(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FriendService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FriendService::Service, ::im::friend_::AddFriendRequest, ::im::friend_::AddFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FriendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::friend_::AddFriendRequest* req,
             ::im::friend_::AddFriendResponse* resp) {
               return service->SendRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FriendService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FriendService::Service, ::im::friend_::HandleFriendRequest, ::im::friend_::HandleFriendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FriendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::friend_::HandleFriendRequest* req,
             ::im::friend_::HandleFriendResponse* resp) {
               return service->RespondToRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FriendService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FriendService::Service, ::im::friend_::GetFriendListRequest, ::im::friend_::GetFriendListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FriendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::friend_::GetFriendListRequest* req,
             ::im::friend_::GetFriendListResponse* resp) {
               return service->GetFriends(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FriendService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FriendService::Service, ::im::friend_::GetFriendRequestsRequest, ::im::friend_::GetFriendRequestsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FriendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::friend_::GetFriendRequestsRequest* req,
             ::im::friend_::GetFriendRequestsResponse* resp) {
               return service->GetPendingRequests(ctx, req, resp);
             }, this)));
}

FriendService::Service::~Service() {
}

::grpc::Status FriendService::Service::ForwardPacket(::grpc::ServerContext* context, const ::im::friend_::FriendPacketRequest* request, ::im::friend_::FriendPacketResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FriendService::Service::SendRequest(::grpc::ServerContext* context, const ::im::friend_::AddFriendRequest* request, ::im::friend_::AddFriendResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FriendService::Service::RespondToRequest(::grpc::ServerContext* context, const ::im::friend_::HandleFriendRequest* request, ::im::friend_::HandleFriendResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FriendService::Service::GetFriends(::grpc::ServerContext* context, const ::im::friend_::GetFriendListRequest* request, ::im::friend_::GetFriendListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FriendService::Service::GetPendingRequests(::grpc::ServerContext* context, const ::im::friend_::GetFriendRequestsRequest* request, ::im::friend_::GetFriendRequestsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace im
}  // namespace friend_
