// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto

#include "push.pb.h"
#include "push.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace im {
namespace push {

static const char* PushService_method_names[] = {
  "/im.push.PushService/NotifyUser",
};

std::unique_ptr< PushService::Stub> PushService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PushService::Stub> stub(new PushService::Stub(channel, options));
  return stub;
}

PushService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_NotifyUser_(PushService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PushService::Stub::NotifyUser(::grpc::ClientContext* context, const ::im::push::NotifyUserRequest& request, ::im::push::NotifyUserResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::push::NotifyUserRequest, ::im::push::NotifyUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NotifyUser_, context, request, response);
}

void PushService::Stub::async::NotifyUser(::grpc::ClientContext* context, const ::im::push::NotifyUserRequest* request, ::im::push::NotifyUserResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::push::NotifyUserRequest, ::im::push::NotifyUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyUser_, context, request, response, std::move(f));
}

void PushService::Stub::async::NotifyUser(::grpc::ClientContext* context, const ::im::push::NotifyUserRequest* request, ::im::push::NotifyUserResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::push::NotifyUserResponse>* PushService::Stub::PrepareAsyncNotifyUserRaw(::grpc::ClientContext* context, const ::im::push::NotifyUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::push::NotifyUserResponse, ::im::push::NotifyUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NotifyUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::push::NotifyUserResponse>* PushService::Stub::AsyncNotifyUserRaw(::grpc::ClientContext* context, const ::im::push::NotifyUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNotifyUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

PushService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PushService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PushService::Service, ::im::push::NotifyUserRequest, ::im::push::NotifyUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::push::NotifyUserRequest* req,
             ::im::push::NotifyUserResponse* resp) {
               return service->NotifyUser(ctx, req, resp);
             }, this)));
}

PushService::Service::~Service() {
}

::grpc::Status PushService::Service::NotifyUser(::grpc::ServerContext* context, const ::im::push::NotifyUserRequest* request, ::im::push::NotifyUserResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace im
}  // namespace push

