#ifndef IM_SERVICE_USER_USER_HPP
#define IM_SERVICE_USER_USER_HPP

#include <odb/core.hxx>
#include <string>
#include <cstdint>

namespace im {
namespace service {
namespace user {

enum class Gender {
    UNKNOWN = 0,
    MALE    = 1,
    FEMALE  = 2,
    OTHER   = 3
};

#pragma db object table("im_users")
class User {
public:
    User() : create_time_(0), last_login_(0), online_(false) {}

    User(const std::string& uid,
         const std::string& account,
         const std::string& password_hash,
         const std::string& nickname,
         const std::string& avatar,
         Gender gender = Gender::UNKNOWN,
         const std::string& signature = "",
         int64_t create_time = 0,
         int64_t last_login = 0,
         bool online = false)
        : uid_(uid), account_(account), password_hash_(password_hash),
          nickname_(nickname), avatar_(avatar), gender_(gender),
          signature_(signature), create_time_(create_time),
          last_login_(last_login), online_(online) {}

    const std::string& uid() const { return uid_; }
    void uid(const std::string& v) { uid_ = v; }

    const std::string& account() const { return account_; }
    void account(const std::string& v) { account_ = v; }

    const std::string& password_hash() const { return password_hash_; }
    void password_hash(const std::string& v) { password_hash_ = v; }

    const std::string& nickname() const { return nickname_; }
    void nickname(const std::string& v) { nickname_ = v; }

    const std::string& avatar() const { return avatar_; }
    void avatar(const std::string& v) { avatar_ = v; }

    Gender gender() const { return gender_; }
    void gender(const Gender v) { gender_ = v; }

    const std::string& signature() const { return signature_; }
    void signature(const std::string& v) { signature_ = v; }

    int64_t create_time() const { return create_time_; }
    void create_time(const int64_t v) { create_time_ = v; }

    int64_t last_login() const { return last_login_; }
    void last_login(const int64_t v) { last_login_ = v; }

    bool online() const { return online_; }
    void online(const bool v) { online_ = v; }

private:
    friend class odb::access;

    // Manual string UID: user IDs are assigned by the application (UUID-based)
    // rather than auto-generated by the database. ODB `auto` requires an integral
    // type and is not appropriate for our distributed ID scheme.
    #pragma db id
    std::string uid_;

    #pragma db not_null unique
    std::string account_;

    // Only the password hash is stored, never the plaintext password.
    // Hashing is performed by the User Service before persistence.
    #pragma db not_null
    std::string password_hash_;

    std::string nickname_;
    std::string avatar_;

    #pragma db value_not_null
    Gender gender_;

    std::string signature_;
    int64_t create_time_;
    int64_t last_login_;
    bool online_;
};

} // namespace user
} // namespace service
} // namespace im

#endif // IM_SERVICE_USER_USER_HPP
